// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_mcmc_sampler_cpp
List run_mcmc_sampler_cpp(NumericVector initial_counts, DataFrame config_info, List target_values, List mcmc_params);
RcppExport SEXP _mateR2_run_mcmc_sampler_cpp(SEXP initial_countsSEXP, SEXP config_infoSEXP, SEXP target_valuesSEXP, SEXP mcmc_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type initial_counts(initial_countsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type config_info(config_infoSEXP);
    Rcpp::traits::input_parameter< List >::type target_values(target_valuesSEXP);
    Rcpp::traits::input_parameter< List >::type mcmc_params(mcmc_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mcmc_sampler_cpp(initial_counts, config_info, target_values, mcmc_params));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mateR2_run_mcmc_sampler_cpp", (DL_FUNC) &_mateR2_run_mcmc_sampler_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_mateR2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
