# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_mcmc_sampler_cpp <- function(initial_counts, config_info, target_values, mcmc_params) {
    .Call(`_mateR2_run_mcmc_sampler_cpp`, initial_counts, config_info, target_values, mcmc_params)
}

